# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('taux_brut', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('taux_net', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(verbose_name='Date de Début')),
                ('dateFin', models.DateField(verbose_name='Date de Fin')),
                ('isValid', models.BooleanField(default=False)),
                ('codeEmploi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=30)),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('date_entree', models.DateField(null=True, verbose_name='date d entrée')),
                ('lieu_naissance', models.CharField(max_length=30, null=True)),
                ('adresse_residence', models.CharField(max_length=255, verbose_name='adresse de residence')),
                ('mail', models.EmailField(default='a@exemple.com', max_length=254)),
                ('tel', models.PositiveIntegerField(default='0')),
                ('num_carte_stagiaire', models.CharField(blank=True, max_length=30, null=True)),
                ('bac', models.CharField(max_length=100, null=True)),
                ('diplome', models.CharField(max_length=100, null=True)),
                ('filiere', models.CharField(max_length=100, null=True)),
                ('mention', models.CharField(max_length=100, null=True)),
                ('etablissement', models.CharField(max_length=100, null=True)),
                ('datevalidation_premiere_annee', models.DateField(blank=True, default='2017-10-20')),
                ('datevalidation_s3', models.DateField(blank=True, default='2017-10-20')),
                ('datevalidation_deuxieme_annee', models.DateField(blank=True, default='2017-10-20')),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire_jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lundi', models.CharField(max_length=4, null=True)),
                ('Mardi', models.CharField(max_length=4, null=True)),
                ('Mercredi', models.CharField(max_length=4, null=True)),
                ('Jeudi', models.CharField(max_length=4, null=True)),
                ('Vendredi', models.CharField(max_length=4, null=True)),
                ('Samedi', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire_semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('Charge_realise', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Charge_realise_modifie', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('chargeHoraire', models.PositiveIntegerField(null=True)),
                ('chargeRealise', models.PositiveIntegerField(null=True)),
                ('seanceRealise', models.PositiveIntegerField(null=True)),
                ('seanceRealiseTemp', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('grade', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=30)),
                ('telephone', models.CharField(default='06', max_length=30)),
                ('diplome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Diplome')),
                ('matiere', models.ManyToManyField(to='app.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seance', models.PositiveIntegerField(blank=True, null=True)),
                ('avancement', models.CharField(blank=True, max_length=20, null=True)),
                ('salle', models.CharField(blank=True, max_length=30, null=True)),
                ('activite', models.CharField(blank=True, max_length=30, null=True)),
                ('is_two', models.BooleanField(default=False)),
                ('date', models.DateField(default='1996-03-23', verbose_name='date seance')),
                ('emploi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.EmploiDuTemps')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Matieres', to='app.Matiere')),
                ('professeur_firstgroup', models.ManyToManyField(blank=True, related_name='Professeur', to='app.Professeur')),
                ('professeur_secondgroup', models.ManyToManyField(blank=True, related_name='_seance_professeur_secondgroup_+', to='app.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semaine', models.PositiveIntegerField()),
                ('dateDebut', models.DateField(verbose_name='Date de Début')),
                ('dateFin', models.DateField(verbose_name='Date de Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Semaine_facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire_semaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Horaire_semaine')),
                ('seance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Seance')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('annee_universitaire', models.CharField(max_length=60, verbose_name='Année univérsitaire')),
                ('dateDebut', models.DateField(verbose_name='Date de Début')),
                ('dateFin', models.DateField(verbose_name='Date de Fin')),
                ('is_full', models.BooleanField(default=False)),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.AddField(
            model_name='semaine',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Semestre'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Semestre'),
        ),
        migrations.AddField(
            model_name='horaire_semaine',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Professeur'),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='horaire_semaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Horaire_semaine'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Promotion'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='semaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Semaine'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Semestre'),
        ),
    ]
