# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_verrou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
    ]
