# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_matiere_seancerealisetemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire_semaine',
            name='Charge_realise',
        ),
        migrations.RemoveField(
            model_name='horaire_semaine',
            name='Charge_realise_modifie',
        ),
        migrations.RemoveField(
            model_name='horaire_semaine',
            name='professeur',
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='Jeudi_modif',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='Mardi_modif',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='Mercredi_modif',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='Samedi_modif',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='Vendredi_modif',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='lundi_modif',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horaire_jour',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Professeur'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.FileField(upload_to='app/static/img'),
        ),
    ]
