# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170703_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
    ]
