# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170706_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='activite',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
