# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170706_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='diplome',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Classement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mention',
            field=models.CharField(max_length=100, null=True, verbose_name='Mention Bac'),
        ),
    ]
