# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170709_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='observation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
