# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_emploidutemps_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire_jour',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
