# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_horaire_jour_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire_jour',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
