# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170711_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire_jour',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
