# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170711_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire_jour',
            name='total_modif',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
